version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: ".github/actions/setup-runner"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: ".github/actions/docker-cache-restore"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: ".github/actions/docker-cache-save"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: ".github/actions/setup-caddy"
    schedule:
      interval: "weekly"
