extends: default

rules:
  document-start: disable
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
  line-length:
    max: 300
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

