log:
  level: info
  job_level: info

runner:
  file: .runner
  env_file: .env
  capacity: 1
  timeout: 3h
  shutdown_timeout: 1h
  insecure: false
  fetch_timeout: 5s
  labels: ["gh-osx:host"]

cache:
  enabled: true
  dir:

host:
  workdir_parent:
